import type { Difficulty } from "./types";

/** ~200 most common English words for typing tests */
export const easyWords: string[] = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "great", "between", "need", "large", "under", "never", "city", "home", "order", "long",
  "hand", "high", "old", "place", "same", "keep", "help", "every", "start", "show",
  "here", "life", "world", "still", "own", "point", "form", "each", "line", "right",
  "move", "thing", "turn", "ask", "late", "run", "small", "name", "house", "part",
  "while", "play", "next", "must", "might", "much", "head", "end", "through", "last",
  "live", "state", "since", "left", "school", "more", "both", "found", "change", "off",
  "does", "learn", "such", "should", "number", "side", "been", "real", "find", "before",
  "few", "read", "where", "case", "little", "call", "why", "set", "try", "put",
  "too", "man", "child", "again", "kind", "went", "many", "around", "write", "word",
  "close", "sure", "let", "light", "far", "begin", "got", "being", "open", "bring",
];

/** Backward-compat alias */
export const commonWords = easyWords;

/** ~220 medium-difficulty words — intentional mix of lengths (5–9 chars) for visual variety */
export const mediumWords: string[] = [
  // 5 chars
  "about", "above", "after", "again", "among", "apply", "basis", "begin",
  "below", "brand", "break", "bring", "build", "carry", "cause", "chair",
  "chain", "check", "chief", "clear", "close", "cover", "court", "cross",
  "daily", "depth", "drawn", "drive", "earth", "enter", "equal", "error",
  "event", "exist", "extra", "faith", "field", "final", "fixed", "floor",
  "focus", "found", "front", "given", "gloss", "grant", "grasp", "great",
  "group", "grown", "guard", "guide", "hence", "index", "inner", "input",
  "issue", "joint", "judge", "known", "label", "large", "later", "layer",
  "learn", "level", "light", "limit", "lined", "local", "logic", "lower",
  "major", "match", "media", "model", "money", "month", "moral", "noted",
  "novel", "offer", "often", "order", "other", "ought", "owned", "panel",
  "paper", "phase", "phone", "pilot", "place", "plain", "plan", "plant",
  "plate", "point", "power", "press", "price", "pride", "prior", "proof",
  "prove", "query", "quick", "quite", "quota", "raise", "rally", "range",
  "ratio", "reach", "ready", "realm", "refer", "reply", "rider", "right",
  "rigid", "rival", "risen", "round", "route", "ruled", "rural", "scale",
  "scene", "scope", "score", "sense", "serve", "setup", "share", "shift",
  "short", "shown", "sight", "skill", "slash", "sleep", "slide", "slope",
  "small", "smart", "solid", "solve", "sound", "space", "spare", "speak",
  "speed", "spend", "split", "stack", "stage", "stake", "stand", "start",
  "state", "stiff", "still", "stock", "store", "storm", "story", "study",
  "style", "swift", "table", "taken", "tasks", "teach", "tends", "theme",
  "there", "threw", "title", "token", "topic", "total", "touch", "trace",
  "track", "trade", "train", "treat", "trial", "tried", "trust", "truth",
  "under", "union", "unite", "until", "usage", "valid", "value", "verse",
  "vital", "voice", "whole", "width", "world", "worth", "write", "yield",
  // 6 chars
  "access", "action", "active", "actual", "affect", "agency", "annual",
  "answer", "assign", "attach", "author", "belong", "border", "bridge",
  "buffer", "bundle", "burden", "camera", "cancel", "choose", "circle",
  "client", "column", "commit", "common", "create", "credit", "custom",
  "damage", "debate", "define", "degree", "demand", "depend", "deploy",
  "design", "detail", "differ", "direct", "divide", "domain", "double",
  "driven", "effect", "enable", "encode", "engine", "entire", "entity",
  "escape", "expect", "expert", "export", "extend", "factor", "failed",
  "filter", "finish", "formal", "format", "gather", "global", "handle",
  "impact", "import", "intent", "kernel", "lambda", "launch", "leader",
  "length", "listen", "lookup", "market", "method", "mirror", "mobile",
  "module", "native", "normal", "notion", "object", "offset", "option",
  "origin", "output", "parent", "parser", "permit", "person", "phrase",
  "player", "policy", "portal", "prompt", "public", "random", "reason",
  "record", "reduce", "reload", "remote", "render", "repair", "repeat",
  "report", "result", "return", "review", "secure", "select", "server",
  "signal", "simple", "single", "sketch", "socket", "source", "spread",
  "sprint", "square", "static", "stream", "strict", "string", "strong",
  "switch", "symbol", "syntax", "system", "target", "throws", "toggle",
  "token", "update", "upload", "vector", "vendor", "verify", "viewer",
  "window", "worker", "writer",
  // 8 chars
  "absolute", "accepted", "accessed", "accurate", "achieved", "activity",
  "analysis", "annotate", "argument", "assemble", "attached", "auditing",
  "blocking", "calendar", "callback", "captured", "category", "computed",
  "consumer", "contains", "contract", "database", "describe", "detected",
  "document", "download", "dynamic", "encoding", "endpoint", "evaluate",
  "explicit", "extended", "external", "feedback", "filename", "finished",
  "function", "generate", "globally", "grouping", "handling", "hardware",
  "identity", "included", "instance", "internal", "interval", "language",
  "licensed", "matching", "measured", "metadata", "multiple", "mutation",
  "numbered", "observed", "optional", "ordering", "override", "paginate",
  "parallel", "platform", "position", "practice", "previous", "property",
  "provided", "received", "redirect", "referred", "register", "released",
  "rendered", "replaced", "required", "resolved", "response", "retained",
  "returned", "rollback", "schedule", "selected", "sequence", "settings",
  "snapshot", "software", "specific", "standard", "strategy", "strongly",
  "template", "terminal", "timeline", "training", "transfer", "triggers",
  "username", "validate", "variable", "workflow",
];

/** ~200 hard words (uncommon/complex) */
export const hardWords: string[] = [
  "algorithm", "ephemeral", "ubiquitous", "paradigm", "ambiguous", "resilient",
  "meticulous", "pragmatic", "eloquent", "arbitrary", "perpetual", "synthesis",
  "anomalous", "benchmark", "cognitive", "consensus", "divergent", "elaborate",
  "formulate", "harmonize", "implement", "juxtapose", "kinematic", "labyrinth",
  "magnitude", "negotiate", "objective", "paradoxical", "quintuple", "reconcile",
  "sovereign", "threshold", "undermine", "vindicate", "whimsical", "xylophone",
  "zealously", "aberration", "benevolent", "capitalize", "deliberate", "exquisite",
  "fabricate", "gratitude", "hierarchy", "illustrate", "jeopardize", "kaleidoscope",
  "legitimate", "manipulate", "nostalgic", "obligation", "peripheral", "quarantine",
  "rhetorical", "supplement", "trajectory", "unanimous", "vulnerable", "wilderness",
  "accentuate", "bureaucracy", "catastrophe", "derivative", "extrapolate", "fluorescent",
  "gregarious", "hypothesis", "idempotent", "jurisprudence", "clandestine", "nonchalant",
  "ostentatious", "prerequisite", "quintessential", "reciprocate", "synchronize",
  "transcendent", "unequivocal", "vivacious", "ambivalent", "bureaucratic", "combustible",
  "dexterity", "eccentricity", "phenomenon", "philanthropy", "polynomial", "melancholy",
  "serendipity", "therapeutic", "meticulous", "conundrum", "dichotomy", "equilibrium",
  "fastidious", "grotesque", "hegemony", "idiosyncrasy", "juxtaposition", "laborious",
  "metamorphosis", "nefarious", "obstinate", "perseverance", "querulous", "rudimentary",
  "surreptitious", "temperament", "ubiquity", "venerable", "acquiesce", "cacophony",
  "ebullient", "fallacious", "impervious", "magnanimous", "obfuscate", "perfunctory",
  "recalcitrant", "sycophant", "tumultuous", "acrimonious", "belligerent", "circumvent",
  "dilapidated", "effervescent", "intransigent", "misanthrope", "pernicious", "recapitulate",
  "superfluous", "unilateral", "vociferous", "capricious", "duplicitous", "ignominious",
  "loquacious", "nomenclature", "panacea", "sanguine", "tenacious", "visceral",
  "anachronism", "convivial", "exacerbate", "facetious", "gratuitous", "incongruous",
  "litigious", "ostentatious", "propensity", "repudiate", "soliloquy", "torpid",
  "unmitigated", "verisimilitude", "antithesis", "compendium", "disparate", "elucidate",
  "frivolous", "harangue", "inscrutable", "luminescent", "obsequious", "precipitous",
  "remunerate", "spurious", "tantamount", "unorthodox", "cavernous", "deleterious",
  "exonerate", "garrulous", "incandescent", "magniloquent", "obstreperous", "perspicacious",
  "reverberate", "surreptitious", "ubiquitous", "variegated", "ameliorate", "capitulate",
  "delineate", "extemporaneous", "grandiloquent", "idiosyncratic", "nomenclature",
];

/** Lookup word pool by difficulty */
export const wordPoolByDifficulty: Record<Difficulty, string[]> = {
  easy: easyWords,
  medium: mediumWords,
  hard: hardWords,
};
